version: '2'
services:
  web:
   image: odoo:12.0
    depends_on:
      - db
    ports:
      - "8070:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
   db: 
   image: postgres:13.2
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PG_DATA=/var/lib/postgresql/data/pgdata
     volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
   volumes:
      - odoo-db-data:
      - odoo-web-data:
    tty: true
    command: -- --dev=reload
    restart: always 
